StarCollege/Areas/Admin/Controllers/EnrollmentController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using StarCollege.DataAccess.Repository.IRepository;
using StarCollege.Models;
using StarCollege.Models.ViewModels;

namespace StarCollege.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class EnrollmentController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;

        public EnrollmentController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        // GET: EnrollmentController
        public IActionResult Index()
        {
            var objEnrollmentList = _unitOfWork.Enrollment.GetAll(includeProperties: "Student,Classroom");

            return View(objEnrollmentList);
        }

        // GET: EnrollmentController/Details/5
        public IActionResult Details(int id)
        {
            return View();
        }

        // GET: EnrollmentController/Create
        public IActionResult CreateUpdate(int? id)
        {
            EnrollmentVM obj = new()
            {
                Enrollment = new(),
                StudentList = _unitOfWork.Student.GetAll().Select(i => new SelectListItem
                {
                    Text = i.FullName,
                    Value = i.Id.ToString()
                }),
                ClassroomList = _unitOfWork.Classroom.GetAll().Select(i => new SelectListItem
                {
                    Text = i.ClassCode,
                    Value = i.Id.ToString()
                })
            };

            if (id == null || id == 0)
            {
                return View(obj);
            }
            else
            {
                obj.Enrollment = _unitOfWork.Enrollment.GetFirstOrDefault(x => x.Id == id);
                return View(obj);
            }                                                                                                                                                                                                                 
        }

        // POST: EnrollmentController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult CreateUpdate(EnrollmentVM obj)
        {
            if (ModelState.IsValid)
            {
                if (obj.Enrollment.Id == 0)
                {
                    _unitOfWork.Enrollment.Add(obj.Enrollment);
                }
                else
                {
                    _unitOfWork.Enrollment.Update(obj.Enrollment);
                }
                _unitOfWork.Save();
                TempData["success"] = "Enrollment created successfully";
                return RedirectToAction("Index");
            }
            return View(obj);
        }

        // GET: EnrollmentController/Delete/5
        public IActionResult Delete(int? id)
        {
            EnrollmentVM objFromDbFirst = new()
            {
                Enrollment = new(),
                StudentList = _unitOfWork.Student.GetAll().Select(i => new SelectListItem
                {
                    Text = i.FullName,
                    Value = i.Id.ToString()
                }),
                ClassroomList = _unitOfWork.Classroom.GetAll().Select(i => new SelectListItem
                {
                    Text = i.ClassCode,
                    Value = i.Id.ToString()
                })
            };

            if (id == null || id == 0)
            {
                return NotFound();
            }

            objFromDbFirst.Enrollment = _unitOfWork.Enrollment.GetFirstOrDefault(u => u.Id == id);

            if (objFromDbFirst == null)
            {
                return NotFound();
            }

            return View(objFromDbFirst);
        }

        // POST: EnrollmentController/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult Delete(int id)
        {
            var obj = _unitOfWork.Enrollment.GetFirstOrDefault(u => u.Id == id);
            if (obj == null)
            {
                return NotFound();
            }

            _unitOfWork.Enrollment.Remove(obj);
            _unitOfWork.Save();
            TempData["success"] = "Enrollment deleted successfully";
            return RedirectToAction("Index");
        }
    }
}

StarCollege/Areas/Admin/Controllers/TeacherController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using StarCollege.DataAccess.Repository.IRepository;
using StarCollege.Models;

namespace StarCollege.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class TeacherController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;

        public TeacherController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        // GET: TeacherController
        public IActionResult Index()
        {
            IEnumerable<Teacher> objTeacherList = _unitOfWork.Teacher.GetAll();
            return View(objTeacherList);
        }

        // GET: TeacherController/Details/5
        public IActionResult Details(int id)
        {
            return View();
        }

        // GET: TeacherController/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: TeacherController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Teacher obj)
        {
            if (ModelState.IsValid)
            {
                _unitOfWork.Teacher.Add(obj);
                _unitOfWork.Save();
                TempData["success"] = "Teacher created successfully";
                return RedirectToAction("Index");
            }
            return View(obj);
        }

        // GET: TeacherController/Edit/5
        public IActionResult Edit(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var objFromDbFirst = _unitOfWork.Teacher.GetFirstOrDefault(u => u.Id == id);

            if (objFromDbFirst == null) return NotFound();

            return View(objFromDbFirst);
        }

        // POST: TeacherController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Teacher obj)
        {
            if (ModelState.IsValid)
            {
                _unitOfWork.Teacher.Update(obj);
                _unitOfWork.Save();
                TempData["success"] = "Teacher updated successfully";
                return RedirectToAction("Index");
            }
            return View(obj);
        }

        // GET: TeacherController/Delete/5
        public IActionResult Delete(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }

            var objFromDbFirst = _unitOfWork.Teacher.GetFirstOrDefault(u => u.Id == id);

            if (objFromDbFirst == null)
            {
                return NotFound();
            }

            return View(objFromDbFirst);
        }

        // POST: TeacherController/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult Delete(int id)
        {
            var obj = _unitOfWork.Teacher.GetFirstOrDefault(u => u.Id == id);
            if (obj == null)
            {
                return NotFound();
            }

            _unitOfWork.Teacher.Remove(obj);
            _unitOfWork.Save();
            TempData["success"] = "Teacher deleted successfully";
            return RedirectToAction("Index");
        }
    }
}

StarCollege/Areas/Admin/Views/Enrollment/CreateUpdate.cshtml
@model StarCollege.Models.ViewModels.EnrollmentVM

<form method="post">
	<div class="border p-3 mt-4">
		<div class="row pb-2">
			<h2 class="text-primary">@(Model.Enrollment.Id != 0 ? "Edit" : "Create") Enrollment</h2>
			<hr />
		</div>
		<div class="mb-3">
			<label asp-for="Enrollment.Score"></label>
			<input asp-for="Enrollment.Score" class="form-control" />
			<span asp-validation-for="Enrollment.Score" class="text-danger"></span>
		</div>
		<div class="mb-3 col-6">
			<label asp-for="Enrollment.StudentId"></label>
			<select asp-for="Enrollment.StudentId" asp-items="@Model.StudentList" class="form-select">
				@*<option disabled selected>--Select Subject--</option>*@
			</select>
			<span asp-validation-for="Enrollment.StudentId" class="text-danger"></span>
		</div>
		<div class="mb-3 col-6">
			<label asp-for="Enrollment.ClassroomId"></label>
			<select asp-for="Enrollment.ClassroomId" asp-items="@Model.ClassroomList" class="form-select">
				@*<option disabled selected>--Select Subject--</option>*@
			</select>
			<span asp-validation-for="Enrollment.ClassroomId" class="text-danger"></span>
		</div>

		<button type="submit" class="btn btn-primary" style="width:150px">@(Model.Enrollment.Id != 0 ? "Update" : "Create")</button>
		<a asp-controller="Enrollment" asp-action="Index" class="btn btn-secondary" style="width:150px">
			Back to List
		</a>
	</div>
</form>

StarCollege/Areas/Admin/Views/Enrollment/Delete.cshtml
@model StarCollege.Models.ViewModels.EnrollmentVM

<form method="post" asp-action="Delete">
	<input asp-for="Enrollment.Id" hidden />
	<div class="border p-3 mt-4">
		<div class="row pb-2">
			<h2 class="text-primary">Delete Enrollment</h2>
			<hr />
		</div>

		<div class="mb-3">
			<label asp-for="Enrollment.Score"></label>
			<input asp-for="Enrollment.Score" disabled class="form-control" />
		</div>
		<div class="mb-3 col-6">
			<label asp-for="Enrollment.StudentId"></label>
			<select asp-for="Enrollment.StudentId" disabled asp-items="@Model.StudentList" class="form-select">
			</select>
		</div>
		<div class="mb-3 col-6">
			<label asp-for="Enrollment.ClassroomId"></label>
			<select asp-for="Enrollment.ClassroomId" disabled asp-items="@Model.ClassroomList" class="form-select">
			</select>
		</div>

		<button type="submit" class="btn btn-danger" style="width:150px">Delete</button>
		<a asp-controller="Enrollment" asp-action="Index" class="btn btn-secondary" style="width:150px">
			Back to List
		</a>
	</div>
</form>

StarCollege/Areas/Admin/Views/Enrollment/Edit.cshtml
@model Teacher

<form method="post" asp-action="Edit">
	<div class="border p-3 mt-4">
		<div class="row pb-2">
			<h2 class="text-primary">Edit Teacher</h2>
			<hr />
		</div>
		<div class="mb-3">
			<label asp-for="FirstMidName"></label>
			<input asp-for="FirstMidName" class="form-control" />
		</div>
		<div class="mb-3">
			<label asp-for="LastName"></label>
			<input asp-for="LastName" class="form-control" />
		</div>
		<div class="mb-3">
			<label asp-for="Title"></label>
			<input asp-for="Title" class="form-control" />
		</div>
		<button type="submit" class="btn btn-primary" style="width:150px">Update</button>
		<a asp-controller="Teacher" asp-action="Index" class="btn btn-secondary" style="width:150px">
			Back to List
		</a>
	</div>
</form>

StarCollege/Areas/Admin/Views/Enrollment/Index.cshtml
@model IEnumerable<Enrollment>
@{
    ViewData["Title"] = "Index";
}

<div class="container p-3">
    <div class="row pt-4">
        <div class="col-6">
            <h2 class="text-primary">Enrollment List</h2>
		</div>
        <div class="col-6 text-end">
            <a asp-controller="Enrollment" asp-action="CreateUpdate" class="btn btn-primary">
               <i class="bi bi-plus-circle"></i> &nbsp; Create New Enrollment
			</a>
		</div>
	</div>
    <br /><br />

<table class="table table-bordered table-striped" style="width:100%">
    <thead>
        <tr>
            <th>
                Student
			</th>
            <th>
                Classroom
			</th>
            <th>
                Score
			</th>
            <th></th>
		</tr>
	</thead>
    <tbody>
        @foreach(var obj in Model)
        {
            <tr>
                <td width="25%">
                    @obj.Student.FullName
				</td>
                <td width="25%">
                    @obj.Classroom.ClassCode
				</td>
                <td width="25%">
                    @obj.Score
				</td>
                <td>
                    <div class="w-75 btn-group" role="group">
                        <a asp-controller="Enrollment" asp-action="CreateUpdate" asp-route-id="@obj.Id"
                        class="btn btn-primary mx-2"> <i class="bi bi-pencil-square"></i> Edit</a>
                        <a asp-controller="Enrollment" asp-action="Delete" asp-route-id="@obj.Id"
                        class="btn btn-danger mx-2"> <i class="bi bi-trash-fill"></i> Delete</a>
					</div>
				</td>
			</tr>
        }
    </tbody>

</table>
</div>