StarCollege/Areas/Admin/Controllers/ClassroomController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using StarCollege.DataAccess.Repository.IRepository;
using StarCollege.Models;
using StarCollege.Models.ViewModels;

namespace StarCollege.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class ClassroomController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;

        public ClassroomController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        // GET: ClassroomController
        public IActionResult Index()
        {
            var objClassroomList = _unitOfWork.Classroom.GetAll(includeProperties: "Course,Teacher");

            return View(objClassroomList);
        }

        // GET: ClassroomController/Details/5
        public IActionResult Details(int id)
        {
            return View();
        }

        // GET: ClassroomController/Create
        public IActionResult CreateUpdate(int? id)
        {
            ClassroomVM obj = new()
            {
                Classroom = new(),
                CourseList = _unitOfWork.Course.GetAll().Select(i => new SelectListItem
                {
                    Text = i.Name,
                    Value = i.Id.ToString()
                }),
                TeacherList = _unitOfWork.Teacher.GetAll().Select(i => new SelectListItem
                {
                    Text = i.FullName,
                    Value = i.Id.ToString()
                })
            };
            
            if (id == null || id == 0)
            {
                return View(obj);
            }
            else
            {
                obj.Classroom = _unitOfWork.Classroom.GetFirstOrDefault(x => x.Id == id);
                return View(obj);
            }                                                                                                                                                                                                                 
        }

        // POST: ClassroomController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult CreateUpdate(ClassroomVM obj)
        {
            if (ModelState.IsValid)
            {
                if (obj.Classroom.Id == 0)
                {
                    _unitOfWork.Classroom.Add(obj.Classroom);
                }
                else
                {
                    _unitOfWork.Classroom.Update(obj.Classroom);
                }
                _unitOfWork.Save();
                TempData["success"] = "Classroom created successfully";
                return RedirectToAction("Index");
            }
            return View(obj);
        }

        // GET: ClassroomController/Delete/5
        public IActionResult Delete(int? id)
        {
            ClassroomVM objFromDbFirst = new()
            {
                Classroom = new(),
                CourseList = _unitOfWork.Course.GetAll().Select(i => new SelectListItem
                {
                    Text = i.Name,
                    Value = i.Id.ToString()
                }),
                TeacherList = _unitOfWork.Teacher.GetAll().Select(i => new SelectListItem
                {
                    Text = i.FullName,
                    Value = i.Id.ToString()
                })
            };

            if (id == null || id == 0)
            {
                return NotFound();
            }

            //var objFromDbFirst = _unitOfWork.Classroom.GetFirstOrDefault(u => u.Id == id);
            objFromDbFirst.Classroom = _unitOfWork.Classroom.GetFirstOrDefault(u => u.Id == id);

            if (objFromDbFirst == null)
            {
                return NotFound();
            }

            return View(objFromDbFirst);
        }

        // POST: ClassroomController/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult Delete(int id)
        {
            var obj = _unitOfWork.Classroom.GetFirstOrDefault(u => u.Id == id);
            if (obj == null)
            {
                return NotFound();
            }

            _unitOfWork.Classroom.Remove(obj);
            _unitOfWork.Save();
            TempData["success"] = "Classroom deleted successfully";
            return RedirectToAction("Index");
        }
    }
}

StarCollege/Areas/Admin/Controllers/TeacherController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using StarCollege.DataAccess.Repository.IRepository;
using StarCollege.Models;

namespace StarCollege.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class TeacherController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;

        public TeacherController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        // GET: TeacherController
        public IActionResult Index()
        {
            IEnumerable<Teacher> objTeacherList = _unitOfWork.Teacher.GetAll();
            return View(objTeacherList);
        }

        // GET: TeacherController/Details/5
        public IActionResult Details(int id)
        {
            return View();
        }

        // GET: TeacherController/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: TeacherController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Teacher obj)
        {
            if (ModelState.IsValid)
            {
                _unitOfWork.Teacher.Add(obj);
                _unitOfWork.Save();
                TempData["success"] = "Teacher created successfully";
                return RedirectToAction("Index");
            }
            return View(obj);
        }

        // GET: TeacherController/Edit/5
        public IActionResult Edit(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var objFromDbFirst = _unitOfWork.Teacher.GetFirstOrDefault(u => u.Id == id);

            if (objFromDbFirst == null) return NotFound();

            return View(objFromDbFirst);
        }

        // POST: TeacherController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Teacher obj)
        {
            if (ModelState.IsValid)
            {
                _unitOfWork.Teacher.Update(obj);
                _unitOfWork.Save();
                TempData["success"] = "Teacher updated successfully";
                return RedirectToAction("Index");
            }
            return View(obj);
        }

        // GET: TeacherController/Delete/5
        public IActionResult Delete(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }

            var objFromDbFirst = _unitOfWork.Teacher.GetFirstOrDefault(u => u.Id == id);

            if (objFromDbFirst == null)
            {
                return NotFound();
            }

            return View(objFromDbFirst);
        }

        // POST: TeacherController/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult Delete(int id)
        {
            var obj = _unitOfWork.Teacher.GetFirstOrDefault(u => u.Id == id);
            if (obj == null)
            {
                return NotFound();
            }

            _unitOfWork.Teacher.Remove(obj);
            _unitOfWork.Save();
            TempData["success"] = "Teacher deleted successfully";
            return RedirectToAction("Index");
        }
    }
}

StarCollege/Areas/Admin/Views/Classroom/CreateUpdate.cshtml
@model StarCollege.Models.ViewModels.ClassroomVM

<form method="post">
	<div class="border p-3 mt-4">
		<div class="row pb-2">
			<h2 class="text-primary">@(Model.Classroom.Id != 0 ? "Edit" : "Create") Classroom</h2>
			<hr />
		</div>
		<div class="mb-3">
			<label asp-for="Classroom.ClassCode"></label>
			<input asp-for="Classroom.ClassCode" class="form-control" />
			<span asp-validation-for="Classroom.ClassCode" class="text-danger"></span>
		</div>
		<div class="mb-3 col-6">
			<label asp-for="Classroom.CourseId"></label>
			<select asp-for="Classroom.CourseId" asp-items="@Model.CourseList" class="form-select">
				@*<option disabled selected>--Select Subject--</option>*@
			</select>
			<span asp-validation-for="Classroom.CourseId" class="text-danger"></span>
		</div>
		<div class="mb-3 col-6">
			<label asp-for="Classroom.TeacherId"></label>
			<select asp-for="Classroom.TeacherId" asp-items="@Model.TeacherList" class="form-select">
				@*<option disabled selected>--Select Subject--</option>*@
			</select>
			<span asp-validation-for="Classroom.TeacherId" class="text-danger"></span>
		</div>

		<button type="submit" class="btn btn-primary" style="width:150px">@(Model.Classroom.Id != 0 ? "Update" : "Create")</button>
		<a asp-controller="Classroom" asp-action="Index" class="btn btn-secondary" style="width:150px">
			Back to List
		</a>
	</div>
</form>

StarCollege/Areas/Admin/Views/Classroom/Delete.cshtml
@model StarCollege.Models.ViewModels.ClassroomVM

<form method="post" asp-action="Delete">
	<input asp-for="Classroom.Id" hidden />
	<div class="border p-3 mt-4">
		<div class="row pb-2">
			<h2 class="text-primary">Delete Teacher</h2>
			<hr />
		</div>
		<div class="mb-3">
			<label asp-for="Classroom.ClassCode"></label>
			<input asp-for="Classroom.ClassCode" disabled class="form-control" />
			<span asp-validation-for="Classroom.ClassCode" class="text-danger"></span>
		</div>
		<div class="mb-3 col-6">
			<label asp-for="Classroom.CourseId"></label>
			<select asp-for="Classroom.CourseId" disabled asp-items="@Model.CourseList" class="form-select">
			</select>
			<span asp-validation-for="Classroom.CourseId" class="text-danger"></span>
		</div>
		<div class="mb-3 col-6">
			<label asp-for="Classroom.TeacherId"></label>
			<select asp-for="Classroom.TeacherId" disabled asp-items="@Model.TeacherList" class="form-select">
			</select>
			<span asp-validation-for="Classroom.TeacherId" class="text-danger"></span>
		</div>
		<button type="submit" class="btn btn-danger" style="width:150px">Delete</button>
		<a asp-controller="Teacher" asp-action="Index" class="btn btn-secondary" style="width:150px">
			Back to List
		</a>
	</div>
</form>

StarCollege/Areas/Admin/Views/Classroom/Edit.cshtml
@model Teacher

<form method="post" asp-action="Edit">
	<div class="border p-3 mt-4">
		<div class="row pb-2">
			<h2 class="text-primary">Edit Teacher</h2>
			<hr />
		</div>
		<div class="mb-3">
			<label asp-for="FirstMidName"></label>
			<input asp-for="FirstMidName" class="form-control" />
		</div>
		<div class="mb-3">
			<label asp-for="LastName"></label>
			<input asp-for="LastName" class="form-control" />
		</div>
		<div class="mb-3">
			<label asp-for="Title"></label>
			<input asp-for="Title" class="form-control" />
		</div>
		<button type="submit" class="btn btn-primary" style="width:150px">Update</button>
		<a asp-controller="Teacher" asp-action="Index" class="btn btn-secondary" style="width:150px">
			Back to List
		</a>
	</div>
</form>

StarCollege/Areas/Admin/Views/Classroom/Index.cshtml
@model IEnumerable<Classroom>
@{
    ViewData["Title"] = "Index";
}

<div class="container p-3">
    <div class="row pt-4">
        <div class="col-6">
            <h2 class="text-primary">Classroom List</h2>
		</div>
        <div class="col-6 text-end">
            <a asp-controller="Classroom" asp-action="CreateUpdate" class="btn btn-primary">
               <i class="bi bi-plus-circle"></i> &nbsp; Create New Classroom
			</a>
		</div>
	</div>
    <br /><br />

<table class="table table-bordered table-striped" style="width:100%">
    <thead>
        <tr>
            <th>
                Teacher
			</th>
            <th>
                Course
			</th>
            <th>
                ClassCode
			</th>
            <th></th>
		</tr>
	</thead>
    <tbody>
        @foreach(var obj in Model)
        {
            <tr>
                <td width="25%">
                    @obj.Teacher.FullName
				</td>
                <td width="25%">
                    @obj.Course.Name
				</td>
                <td width="25%">
                    @obj.ClassCode
				</td>
                <td>
                    <div class="w-75 btn-group" role="group">
                        <a asp-controller="Classroom" asp-action="CreateUpdate" asp-route-id="@obj.Id"
                        class="btn btn-primary mx-2"> <i class="bi bi-pencil-square"></i> Edit</a>
                        <a asp-controller="Classroom" asp-action="Delete" asp-route-id="@obj.Id"
                        class="btn btn-danger mx-2"> <i class="bi bi-trash-fill"></i> Delete</a>
					</div>
				</td>
			</tr>
        }
    </tbody>

</table>
</div>