StarCollege/Areas/Admin/Controllers/SubjectController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using StarCollege.DataAccess.Repository.IRepository;
using StarCollege.Models;

namespace StarCollege.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class SubjectController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;

        public SubjectController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        // GET: SubjectController
        public IActionResult Index()
        {
            IEnumerable<Subject> objSubjectList = _unitOfWork.Subject.GetAll();
            return View(objSubjectList);
        }

        // GET: SubjectController/Details/5
        public IActionResult Details(int id)
        {
            return View();
        }

        // GET: SubjectController/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: SubjectController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Subject obj)
        {
            if (ModelState.IsValid)
            {
                _unitOfWork.Subject.Add(obj);
                _unitOfWork.Save();
                TempData["success"] = "Subject created successfully";
                return RedirectToAction("Index");
            }
            return View(obj);
        }

        // GET: SubjectController/Edit/5
        public IActionResult Edit(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var objFromDbFirst = _unitOfWork.Subject.GetFirstOrDefault(u => u.Id == id);

            if (objFromDbFirst == null) return NotFound();

            return View(objFromDbFirst);
        }

        // POST: SubjectController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Subject obj)
        {
            var errors = ModelState
            .Where(x => x.Value.Errors.Count > 0)
            .Select(x => new { x.Key, x.Value.Errors })
            .ToArray();
            if (ModelState.IsValid)
            {
                _unitOfWork.Subject.Update(obj);
                _unitOfWork.Save();
                TempData["success"] = "Subject updated successfully";
                return RedirectToAction("Index");
            }
            return View(obj);
        }

        // GET: SubjectController/Delete/5
        public IActionResult Delete(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }

            var objFromDbFirst = _unitOfWork.Subject.GetFirstOrDefault(u => u.Id == id);

            if (objFromDbFirst == null)
            {
                return NotFound();
            }

            return View(objFromDbFirst);
        }

        // POST: SubjectController/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult Delete(int id)
        {
            var obj = _unitOfWork.Subject.GetFirstOrDefault(u => u.Id == id);
            if (obj == null)
            {
                return NotFound();
            }

            _unitOfWork.Subject.Remove(obj);
            _unitOfWork.Save();
            TempData["success"] = "Subject deleted successfully";
            return RedirectToAction("Index");
        }
    }
}

StarCollege/Areas/Admin/Views/Subject/Create.cshtml
@model Subject

<form method="post">
	<div class="border p-3 mt-4">
		<div class="row pb-2">
			<h2 class="text-primary">Create Subject</h2>
			<hr />
		</div>
		<div class="mb-3">
			<label asp-for="Name"></label>
			<input asp-for="Name" class="form-control" />
			<span asp-validation-for="Name" class="text-danger"></span>
		</div>
		<div class="mb-3">
			<label asp-for="Department"></label>
			<input asp-for="Department" class="form-control" />
			<span asp-validation-for="Department" class="text-danger"></span>
		</div>
		<button type="submit" class="btn btn-primary" style="width:150px">Create</button>
		<a asp-controller="Subject" asp-action="Index" class="btn btn-secondary" style="width:150px">
			Back to List
		</a>
	</div>
</form>

StarCollege/Areas/Admin/Views/Subject/Delete.cshtml
@model Subject

<form method="post" asp-action="Delete">
	<input asp-for="Id" hidden />
	<div class="border p-3 mt-4">
		<div class="row pb-2">
			<h2 class="text-primary">Delete Category</h2>
			<hr />
		</div>
		<div class="mb-3">
			<label asp-for="Name"></label>
			<input asp-for="Name" disabled class="form-control" />
		</div>
		<div class="mb-3">
			<label asp-for="Department"></label>
			<input asp-for="Department" disabled class="form-control" />
		</div>
		<button type="submit" class="btn btn-danger" style="width:150px">Delete</button>
		<a asp-controller="Category" asp-action="Index" class="btn btn-secondary" style="width:150px">
			Back to List
		</a>
	</div>
</form>

StarCollege/Areas/Admin/Views/Subject/Edit.cshtml
@model Subject

<form method="post" asp-action="Edit">
	<div class="border p-3 mt-4">
		<div class="row pb-2">
			<h2 class="text-primary">Edit Category</h2>
			<hr />
		</div>
		<div class="mb-3">
			<label asp-for="Name"></label>
			<input asp-for="Name" class="form-control" />
		</div>
		<div class="mb-3">
			<label asp-for="Department"></label>
			<input asp-for="Department" class="form-control" />
		</div>
		<button type="submit" class="btn btn-primary" style="width:150px">Update</button>
		<a asp-controller="Category" asp-action="Index" class="btn btn-secondary" style="width:150px">
			Back to List
		</a>
	</div>
</form>

StarCollege/Areas/Admin/Views/Subject/Index.cshtml
@model IEnumerable<Subject>
@{
    ViewData["Title"] = "Index";
}

<div class="container p-3">
    <div class="row pt-4">
        <div class="col-6">
            <h2 class="text-primary">Subject List</h2>
		</div>
        <div class="col-6 text-end">
            <a asp-controller="Subject" asp-action="Create" class="btn btn-primary">
               <i class="bi bi-plus-circle"></i> &nbsp; Create New Subject
			</a>
		</div>
	</div>
    <br /><br />

<table class="table table-bordered table-striped" style="width:100%">
    <thead>
        <tr>
            <th>
                Name
			</th>
            <th>
                Department
			</th>
            <th></th>
		</tr>
	</thead>
    <tbody>
        @foreach(var obj in Model)
        {
            <tr>
                <td width="50%">
                    @obj.Name
				</td>
                <td width="30%">
                    @obj.Department
				</td>
                <td>
                    <div class="w-75 btn-group" role="group">
                        <a asp-controller="Subject" asp-action="Edit" asp-route-id="@obj.Id"
                        class="btn btn-primary mx-2"> <i class="bi bi-pencil-square"></i> Edit</a>
                        <a asp-controller="Subject" asp-action="Delete" asp-route-id="@obj.Id"
                        class="btn btn-danger mx-2"> <i class="bi bi-trash-fill"></i> Delete</a>
					</div>
				</td>
			</tr>
        }
    </tbody>

</table>
</div>